### ISSUE TITLE
Documentation - "How to use" section should show what to do next

### ISSUE THREAD

**Issue by danyork** [SIDN/entrada#106]
Hi, I followed the "How to use" instructions found both on https://hub.docker.com/r/sidnlabs/entrada and https://github.com/SIDN/entrada . I copied the `h2-local` docker-compose file and renamed it to `docker-compose.yml`. I edited it to include the tag of the image.  I did `docker-compose up` ... and I can see from `docker ps` that I have the container up and running on port 8080.

However, now that I have it running... I don't know what to do!  I tried to connect to http://localhost:8080/ , but I got a 404. The website text says "_For more more details about deployment and available onfiguration options see the ENTRADA website._", but when I went to https://entrada.sidnlabs.nl/ I looked around through the various links and couldn't figure out what to do next.

Did I do something wrong? _Should_ I be able to go to http://localhost:8080/ ? Is there another URL to use?

If I did everything correctly, then I would suggest that the "How to use" section please be extended to say what someone should do next.

Perhaps something like (using the Docker Hub text):

--------
How to use

Pull the docker image from Docker hub.

   docker pull sidnlabs/entrada:<tag>

Download one of the example Docker Compose scripts
Modify the environment variables for hostnames and filesystem paths to fit your requirements and then start the container.

   docker-compose up -d

Connect to [ URL ] to start using Entrada.
(or 'Read [link]these steps[/link] to understand what to do next'
or 'You can now execute commands using ...... '  or whatever it is we need to do next!)

For more information about the configuration options see the ENTRADA website 

--------

Thanks for making the tool available as a Docker container. It's a great idea to try out for testing.

**Comment by mwullink** [comment]
Added more detailed instructions on the entrada website (https://entrada.sidnlabs.nl/about/installation/)
The readme in the github repo will refer to the more detailed instructions.
