### ISSUE TITLE
GeoLite2 not downloading

### ISSUE THREAD

**Issue by viniciosbarretos** [SIDN/entrada#107]
Hello,

Recently GeoMind changed their privacy policies and the docker is not initiating. It is with the following error: "Errror executing HTTP GET request for: https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz"

Thanks

**Comment by mwullink** [comment]
Hmm login is now required for free version of MaxmInd, this seems to work identical to the paid version.
I will test this and update the documentation

**Comment by mimilos** [comment]
Hi,
I  tried  to install Entrada, but I have an error:
"Caused by: java.lang.RuntimeException: No valid Maxmind license key found, provide key for either the free of paid license."
Tried versions 2.0.20, 2.1.0, ...

How to solve this problem?

**Comment by mwullink** [comment]
Hi,

You need to signup for a free Maxmind account and create a license key, see here for more info: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

The you need to configure the license key, you can just add the the following to your docker-compose.yml

- GEOIP_MAXMIND_LICENSE_FREE=<my-license-key-here>


replace "<my-license-key-here>" with the actual key


for more info see: https://entrada.sidnlabs.nl/about/configuration/#ip-database

Hope this helps,

Best,

Maarten


--
Maarten Wullink | Research Engineer
SIDN | Meander 501 | 6825 MD | Postbus 5022 | 6802 EA | ARNHEM
T +31 (0)26 352 55 45 | M +31 (0)6 21 26 87 55
maarten.wullink@sidn.nl | www.sidn.nl
pgp key: http://pgp.mit.edu/pks/lookup?op=get&search=0x4F2A495C4B1BF08B

**Comment by mimilos** [comment]
Hi, Thanks for the quick information. It helpt me a lot.
I implemented key in the docker-compose file and Entrada is running. I used the test version (H2 and local file system). In log files, I see pcap files are used and there are no errors. 
When I try to use port 8080 (localy or on Docker host) I have this error page:

"Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Mon Mar 09 14:44:48 UTC 2020
There was an unexpected error (type=Not Found, status=404).
No message available"

Can you tell me what may be the problem?
Do I need to install Graphite (can I use Docker image) ?

Best, 
Milos

**Comment by mwullink** [comment]
Hi,


> Hi, Thanks for the quick information. It helpt me a lot.
> I implemented key in the docker-compose file and Entrada is running. I used the test version (H2 and local file system). In log files, I see pcap files are used and there are no errors.
> When I try to use port 8080 (localy or on Docker host) I have this error page:

there is no web frontend for entrada, just a very limited API at the moment, see: https://entrada.sidnlabs.nl/api/status/

Your pcap data is picked up from the input directory and transformed to parquet and saved in the output directory.

> 
> "Whitelabel Error Page
> 
> Can you tell me what may be the problem?

there is no problem, because there is no web interface

> Do I need to install Graphite (can I use Docker image) ?

Graphite is optional you don’t need it for entrada to work.



Best,

Maarten
