### ISSUE TITLE
Feature request: add reverse DNS field to resolver's IP

### ISSUE THREAD

**Issue by gmmoura** [SIDN/entrada#125]
Add a column on the DNS table to store the reverse dns (if exists ) of the `src`:

```
src,r_dns
1.1.1.1,one.one.one.one.one
```

**Comment by mwullink** [comment]
doing reverse during pcap conversion takes too much time.
best thing would be to do this out of band and then combine those results wiht the data when doing analsys.

so sorry, not going to implement this for now.
