### ISSUE TITLE
Memory leak when not closing org/apache/hadoop/fs/FileSystem.java

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada#126]
After using the FileSystem the close() method must be called to release resources and cached objects.
if this is not done then memory wil be full with cache FileSystem objects.

see:  https://github.com/hanborq/hadoop/blob/master/src/core/org/apache/hadoop/fs/FileSystem.java

fix: HDFSFileManagerImpl must close all instances of FileSystem after use

**Comment by thomasdupas** [comment]
Not sure if this is fixed actually, did you notice an improvement?
Tracking it a bit lately, and this is for example after running for a few days.

<img width="898" alt="Screenshot 2020-06-04 at 13 56 30" src="https://user-images.githubusercontent.com/3289765/83753837-48b8bf00-a66b-11ea-820a-0976f705d8a6.png">
<img width="440" alt="Screenshot 2020-06-04 at 13 57 01" src="https://user-images.githubusercontent.com/3289765/83753845-4bb3af80-a66b-11ea-95d4-c2e7dda628dd.png">

Didn't have time yet for a fix attempt, will put it on my list

**Comment by mwullink** [comment]
I did see improvement but you are right that just calling close() on the filesystem is not clearing all the cached entries. Now also calling closeAll() to make sure all cached entries are removed when fs method is completed.
