### ISSUE TITLE
memory leak due to trailing Hadoop configuration objects

### ISSUE THREAD

**Issue by thomasdupas** [SIDN/entrada#134]
We've been dealing with OOM conditions lately, but didn't delve into the specifics yet up till now.
There's a memory leak caused by a new instance of org.apache.hadoop.conf.Configuration created at every parquet interaction.
On instances with smaller heap sizes this quickly created an OOM condition (10 457 instances resulted in ~700MB heap for example).

We've tested the fix on our end for the past week, seems solved without side effects.

Pre: 
![image-2020-10-19-14-01-20-429](https://user-images.githubusercontent.com/3289765/96449713-8cc0f080-1215-11eb-81bb-96d831789bf0.png)

Post:
![image-2020-10-19-14-01-55-649](https://user-images.githubusercontent.com/3289765/96449729-92b6d180-1215-11eb-845f-875c01ed9a2f.png)

**Comment by mwullink** [comment]
This has been fixed, see pull request: https://github.com/SIDN/entrada/pull/135
