### ISSUE TITLE
feature request: add TCP teardown metric

### ISSUE THREAD

**Issue by gmmoura** [SIDN/entrada#138]
`tcp_rtt_hs` measures the RTT between client and auth server at the handshake

it would be nice to have a metric that measure the same during the teardown of the connection.

**Comment by mwullink** [comment]
This is not possible at the moment without major refactor, at the moment the client FIN is received all DNs packets from the payload are already sent to the upper layer for further processing. This means there are no DNS messages to attach the timing information to.

closing issue.
