### ISSUE TITLE
install doc bug (wrong script name in cron jobs)

### ISSUE THREAD

**Issue by gryphius** [SIDN/entrada#15]
http://entrada.sidnlabs.nl/docs/introduction/install/#schedule-jobs

```
[...]
#Update staging stats every hour
0 * * * * . config.sh && run_05_update_stats_staging >> $ENTRADA_LOG_DIR/entrada-update-stats.log 2>&1
```
this is missing the `.sh` at the end, the actual filename is `run_05_update_stats_staging.sh`

**Comment by mwullink** [comment]
fixed typo.
