### ISSUE TITLE
add configure option for parent domains

### ISSUE THREAD

**Issue by MikeAT** [SIDN/entrada#16]
Currently the mapping from qname to domain is static (the domain is the 2nd label + the tld). This is fine if  a TLD allows only registrations under the TLD itself, but some TLDs (like AT) allow registration under 2nd level domains as well (for .AT you can register under .at but also under .co.at or .or.at).

In the current implementation all qnames for domain1.co.at and domain2.co.at are mapped to the domain 'co.at' which is wrong. 

It would be great if there is a configure option where you can define the valid parent domains for your installation and the getDomain method returns the correct domain for the qname.

**Comment by MikeAT** [comment]
my quick and dirty fix for .at looks like this:

diff --git a/dnslib4java/src/main/java/nl/sidn/dnslib/util/NameUtil.java b/dnslib4java/src/main/java/nl/sidn/dnslib/util/NameUtil.java
index 092e5fa..ec902dc 100644
--- a/dnslib4java/src/main/java/nl/sidn/dnslib/util/NameUtil.java
+++ b/dnslib4java/src/main/java/nl/sidn/dnslib/util/NameUtil.java
@@ -22,6 +22,8 @@
 package nl.sidn.dnslib.util;
 
 import java.util.regex.Pattern;
+import java.util.ArrayList;
+import java.util.List;
 
 import org.apache.commons.lang3.StringUtils;
 
@@ -61,6 +63,16 @@ public class NameUtil {
                        if( parts.length == 1){
                                return new Domaininfo(parts[parts.length-1],parts.length);
                        }
+                       /* .at support 2nd level pdos */
+                       ArrayList<String> valid2ndlevels = new ArrayList<String>();
+                       valid2ndlevels.add("co");
+                       valid2ndlevels.add("or");
+                       valid2ndlevels.add("ac");
+                       valid2ndlevels.add("gv");
+                       valid2ndlevels.add("priv");
+                       if (parts.length > 2 && valid2ndlevels.contains(parts[parts.length-2]))  {
+                               return new Domaininfo(parts[parts.length-3] + "." + parts[parts.length-2] + "." + parts[parts.length-1]
+                       }
                        //all other
                        return new Domaininfo(parts[parts.length-2] + "." + parts[parts.length-1],parts.length);
                }
diff --git a/dnslib4java/src/test/java/nl/sidn/dnslib/util/NameUtilTest.java b/dnslib4java/src/test/java/nl/sidn/dnslib/util/NameUtilTe
index 6b68a6c..f055fa7 100644
--- a/dnslib4java/src/test/java/nl/sidn/dnslib/util/NameUtilTest.java
+++ b/dnslib4java/src/test/java/nl/sidn/dnslib/util/NameUtilTest.java
@@ -41,6 +41,15 @@ public class NameUtilTest {
                Assert.assertEquals(null, NameUtil.getDomain("").name);
                Assert.assertEquals(null, NameUtil.getDomain(null).name);
 
+               Assert.assertEquals("co.at", NameUtil.getDomain("co.at.").name);
+               Assert.assertEquals("domain.co.at", NameUtil.getDomain("domain.co.at.").name);
+               Assert.assertEquals("domain.co.at", NameUtil.getDomain("www.domain.co.at.").name);
+               Assert.assertEquals("domain.or.at", NameUtil.getDomain("www.domain.or.at.").name);
+               Assert.assertEquals("domain.gv.at", NameUtil.getDomain("www.domain.gv.at.").name);
+               Assert.assertEquals("domain.ac.at", NameUtil.getDomain("www.domain.ac.at.").name);
+               Assert.assertEquals("domain.priv.at", NameUtil.getDomain("www.domain.priv.at.").name);
+               Assert.assertEquals("domainco.at", NameUtil.getDomain("www.domainco.at.").name);
+
        }
 
        @Test

**Comment by mwullink** [comment]
Thanks for your example code, i changed the code somewhat so it will support all tld suffixes. There might also be registries offering registrations at the 4th level.

this will be released in entrada 0.0.7
