### ISSUE TITLE
Possible problem inporting pcap files with truncated packets

### ISSUE THREAD

**Issue by mtoma** [SIDN/entrada#39]
At Afnic we truncate the DNS packets at 256 bytes when capturing them with pcapdump for storage and network bandwidth saving purposes.
All packets from those files seem to be considered corrupt by entrada.
Attached is an example pcap
[mezzo-dns.bru.nic.fr-d.nic.fr-dns-SAMPLING-1.2016-12-06.12:30.pcap.gz](https://github.com/SIDN/entrada/files/634263/mezzo-dns.bru.nic.fr-d.nic.fr-dns-SAMPLING-1.2016-12-06.12.30.pcap.gz)
 file.

**Comment by mwullink** [comment]
cutting off the packets at 256 bytes will cause the decoder to read too far in memory.
it will try to read more bytes than are actually available, this will cause an exception.
and the dns packets will not be stored in the database as a result.

the allowFaill option in the Message constructor can be used to allow partially valid packets.
this option is now only used for decoding dns packets wrapped in icmp packets, these are also truncated at 8 bytes i believe.

we could:

1) make this option available through a configuration option.
OR
2) always allow partially valid dns packets to be stored in the database.
most of the interesting stuff is in the header which will fit within the 256 bytes.



more info: 
class:  nl.sidn.pcap.decoder.DnsDecoder
method: public void decode(DNSPacket packet, byte[] payload, boolean allowFaill) {
	
		NetworkData nd = null;
		Message dnsMessage = null;

		nd = new NetworkData(payload);
		try {
			dnsMessage = new Message(nd, allowFaill); <<----

**Comment by mwullink** [comment]
closed due to inactivity
