### ISSUE TITLE
Entrada settings duplicate entry in entrada-settings.properties 

### ISSUE THREAD

**Issue by gdalbergs** [SIDN/entrada#43]
The configuration file entrada-settings.properties has duplicate entry for key cache.timeout.tcp.flows.
Fragment from file:

    #minutes before tcp flows cache entries timeout
    cache.timeout.tcp.flows=5
    #minutes before fragmented ip cache entries timeout
    cache.timeout.tcp.flows=1

Estimated results: one cache value not being set causes it to be the default.

**Comment by mwullink** [comment]
the 2nd "cache.timeout.tcp.flows=1" was a type, should have been: "cache.timeout.ip.fragmented=1"
