### ISSUE TITLE
Configuration option looks like not taking effect!

### ISSUE THREAD

**Issue by gdalbergs** [SIDN/entrada#44]
I have a functional entrada setup. The version I use is 0.0.8.

I have changed all 3 cache values in entrada-settings.properties configuration file to 10 minutes.
 #minutes before dns cache entries timeout
 cache.timeout=10
 #minutes before tcp flows cache entries timeout
 cache.timeout.tcp.flows=10
 #minutes before fragmented ip cache entries timeout
 cache.timeout.ip.fragmented=10
The metrics I see in my grafana graphs have a significant drop every minute at the same 10 second mark. The dns.request.count value is in the range of 30 000 to 50 000 requests, but each minute at the 30 second mark the value drops to about 500. I`ve also noticed the metric pattern being reshaped at the 30 second mark after an update, which indicates that graphite is receiving a value for an already set key + timestamp pair. Since it is happening every minute, it seems like one of the cache values is still being used as 1 minute, which is the default.

This makes me think that one of the 3 cache values is not being affected by the configuration file, since this is the same behavior that is described in issue #42.
I can`t be sure since I can`t dump the values of the variables, but it definitely looks like the case.

**Comment by mwullink** [comment]
fixed with issue #42
