### ISSUE TITLE
Moving from staging to warehouse not working properly

### ISSUE THREAD

**Issue by gdalbergs** [SIDN/entrada#45]
Good day to you!
I`ve noticed another (from my perspective) bug in the code.
I am using entrada 0.0.8.
The problem is in run_03_staging_to_warehouse.sh script.

The "-k" option added to impala-sehll command on line 57 feels out of place and should be dependent on configuration files. I`ve disabled kerberos in configuration files, but moving to warehouse is not working since the option always requires kerberos.

This prevents any data being moved to warehouse.

For now I`ve just deleted that option from the script, but I think that this should be addressed.
Thank You for your work!

**Comment by gryphius** [comment]
This bug is fixed in https://github.com/SIDN/entrada/commit/c0a032ea1f6257f750a59bd5339c8fd2a583679c , make sure you're using the latest version from git

**Comment by gdalbergs** [comment]
Ok. Thank you.
I was planning on switching anyway because of bug #42.
