### ISSUE TITLE
hdfs root path /user/hive/entrada/staging does not exist, stop

### ISSUE THREAD

**Issue by songlinjian** [SIDN/entrada#46]
I encoutner that error msg when run  `. config.sh && run_02_partial_loader_bootstrap.sh` , and it stoped.

I found there is no directory beneath the `/user/hive/entrada/`. I wonder where staging directory is created? I mean which step?  create_impala_tables.sh or run_00, 01 or 02 script?

**Comment by mwullink** [comment]
these directories should be created when the tables are created with the following script.

entrada-latest/scripts/install/create_impala_tables.sh

**Comment by songlinjian** [comment]
> these directories should be created when the tables are created with the following script.
> entrada-latest/scripts/install/create_impala_tables.sh

But the directories is not made after running `create_impala_tables.sh`. is there any permission needed to create that directories? I will trace the problem in the code `create_impala_tables.sh` and return soon.

**Comment by mwullink** [comment]
any news on this?
can we close the issue?

**Comment by mwullink** [comment]
not enough info to proceed ont his issue.
closing it for now. if more details are provided we cal reopen the issue.
