### ISSUE TITLE
Store DNS flags for both query and response

### ISSUE THREAD

**Issue by jakopako** [SIDN/entrada#47]
Currently, some of the DNS header flags that are being stored by Entrada belong to the query header and others belong to the response header. E.g. the rd flag belongs to the query while the tc flag belongs to the reponse. That makes sense since those flags should only be used in the query, respectively the response. But say there is a faulty system sending queries with the tc header set to true. This cannot be seen in the data stored by Entrada. Actually, I encountered a case like that, so I was wondering whether the DNS header flags could be stored for both the question and the answer.

**Comment by gryphius** [comment]
I'm adding support in https://github.com/SIDN/entrada/pull/53
So far I've only added fields in the question which shouldn't be there: 
 * TC bit
 * RA bit
 * AD bit
 * RCode
Is there a good use case to store weird stuff from the answer as well? (eg. RD bit). As long as Entrada does not handle recursive traffic I don't see much sense in adding this, but it would be easy to do.

@jakopako do you still have the pcap with the broken questions to test my changes?

**Comment by mwullink** [comment]
also related to this issue:
8dfe9ccd12628bcf68bb05aff6a9b9b2a1884e3d
