### ISSUE TITLE
Entrada partially stops converting pcaps to parquet

### ISSUE THREAD

**Issue by jakopako** [SIDN/entrada#48]
After having used Entrada for a couple of weeks now and feeding it with about 330million queries a day, we are quite happy with the program and it mostly works very well! For some reason though, occasionally Entrada seems to get congested, meaning that for one or more nameservers the pcap-files aren't processed anymore after having been copied to the processing directory. To me the logs did not reveal any information that would lead to a solution of the problem. At one point in time the logs say that there are no new pcaps for the respective server and the next moment when the same server is referenced again in the logs, it says that the process is already running and therefore no new process is started. From that point on the pcaps accumulate in the processing directory. A temporary fix for the problem was to delete the temporary file run_02_partial_loader_[server].ch and all the unprocessed pcaps. But after some time the same problem reoccurs.

**Comment by mwullink** [comment]
Hi,

Maybe there is a bug in the Java code that causes a thread to hang. When this issue occurs do you still see a live process for the nameserver. e.g.  ?

/staging/loader/logic/entrada/scripts/run/run_02_partial_loader.sh ns1.my.tld /staging/loader/logic/config/entrada-settings.properties

And if there still is the run_02_partial_loader_[server].ch temp file then the Java decoder is most likely hanging.

If possible can you send me the pcap file the decoder was working on last? i can try to debug the decoder using that pcap file to see where it hangs.

**Comment by mwullink** [comment]
entrada has changed a lot since this issue was created, not hearing anything about this from other users, so its probably fixed?

if not, then please let me know, for now closing this issue without further action.
