### ISSUE TITLE
Google Public DNS: Using dig in place of HTML crawler

### ISSUE THREAD

**Issue by moritzcm** [SIDN/entrada#60]
In GoogleResolverCheck.java we crawl the list of Google Public DNS resolvers from a HTML website.

Google also publishes the list in DNS: 
dig TXT locations.publicdns.goog.

I assume that this list might be more up-to-date and a the DNS lookup might be less prone to crawling errors due to a redesign of the website.

**Comment by mwullink** [comment]
awesome, did not know this. maybe newly added by goog?

will add this issue to the next release.

**Comment by mwullink** [comment]
now using dns lookup for Goog: dig TXT locations.publicdns.goog
and getting json data file from opendns website: https://www.opendns.com/network-map-data
