### ISSUE TITLE
OpenDNS resolver loading fails

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada#61]
2017-11-08 11:56:34,035-main--ERROR-nl.sidn.pcap.ip.GoogleResolverCheck:No OpenDNS resolvers found at url: https://www.opendns.com/data-center-locations/

**Comment by mdavids** [comment]
Try: https://www.opendns.com/network-map-data ;-)

**Comment by mwullink** [comment]
https://www.opendns.com/network-map-data

**Comment by mwullink** [comment]
fixed 
also opendns now uses Lets Encrypt cert, if using < Java 8  then add the CA certs to the keystore otherwise the cert will not be valid. 

add LE CA certs with:
https://gist.githubusercontent.com/Firefishy/109b0f1a90156f6c933a50fe40aa777e/raw/15926be913682876ae68bb4f71e489bc53feaae3/install-letsencrypt-in-jdk.sh
