### ISSUE TITLE
Geolocation (Country)

### ISSUE THREAD

**Issue by mashal1996** [SIDN/entrada#92]
Geolocation (Country)
I want to display the country as shown in the example of dashboard but the problem that graphite does not provide the country count. it is just will display the total country: 
entrada.country.count  
but i want for example
entrada.country.US.request.count
does this have something related the carbon ??
please let me know as soon as possible

**Comment by mwullink** [comment]
Hi,

Are you using the latest version of entrada?
then you should have metrics with country name.

e.g.

entrada.geo.country.US.ns.*

or

aliasByNode(minimumAbove(consolidateBy(entrada.geo.country.*.ns.$NS, 'average'), 0), 3)

**Comment by mashal1996** [comment]
it is not the last version .
is there any way to update it without losing the current data.

**Comment by mwullink** [comment]
Ah ok, the country names are only in the latest entrada 2.x version.

when you say "without losing the current data." 

do you mean the Parquet data of the metrics data in Graphite?

if you want to keep the old Parquet data with the new version?

you can upgrade the old location, see: https://github.com/SIDN/entrada/wiki/Upgrade

Or save the new data in a new HDFS location and database.

-  configure ENTRADA to save the Parquet data in another HDFS location 
- use a different Impala table name e.g. entrada2


if you want to keep the old metrics with the new version?
the latest version will not delete the old metrics and will just add additional metrics.

**Comment by mashal1996** [comment]
Okk..
but the latest version released is v-0.1.3
where can I find  (entrada 2.x version) ??

**Comment by mwullink** [comment]
ah i forgot to update the releases page, it was still a draft release.

https://github.com/SIDN/entrada/releases/tag/2.0.1

**Comment by mashal1996** [comment]
Thank you very much
