### ISSUE TITLE
Whisper Database

### ISSUE THREAD

**Issue by mashal1996** [SIDN/entrada#93]
Hi ,
I have two quesions:
1-In case we lost Whisper files , is there any way to regenerate the files again from impala DB.

2- I want to change the timestamp of all  metrics, instade using the arrival time, I want it to be the timestamp of the (DNS) packet (the timestamp of the packet in impala table).

I hope you understand me,
regards

**Comment by mwullink** [comment]
1 - you can create your own metrics, see: https://github.com/SIDN/entrada/wiki/Monitoring#additional-metrics

but having entrada recreate the metrics for data that is already processed, is not possible.

2 - entrada uses the timestamp (utc) of the packets as found in the pcap file, NOT the timestamp of the time the pcap data was processed.

**Comment by mashal1996** [comment]
1- so, I can use cron to run the script, right??
if yes, do I have to run it every minute ??


2- but grafana and grphite shows the timestamp of the time the pcap data was processed, what do you think the problem is ?.

**Comment by mwullink** [comment]
yes you can use cron and run the script at any interval to create metrics for a period.

ah, you mean the [example script](https://github.com/SIDN/entrada/wiki/Monitoring#additional-metrics) use the current timestamp?

you can fix this by changing the sql-query to include the timestamp from the database ( select time ... from ...)
each row in the result of the sql-query should be in [graphite format](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol)
you can then send this directly to graphite.

**Comment by mashal1996** [comment]
no, I don't mean the example script . I am using entrada 0.1.3, the problem with this version is it uses the current timestamp when the packet was processed. but I want to use the timestamp of the packet as what we have in the last version.

**Comment by mwullink** [comment]
ah yes i remember, the 0.x versions only use the packet timestamp for the number of queries metric. all others use processing time. entrada 2.x uses the packet timestamp

the only way to get the packet timestamp in graphite using entrada 0.x is to create your own impala queries and format the results as graphite data and send it to graphite. as in the example script.

**Comment by mashal1996** [comment]
Ok, thank you ,
when do you release the installation document for the new version?

**Comment by mwullink** [comment]
the documentation is available on the Github wiki, if you are missing anything or have questions.
just let us know at entrada@sidn.nl

https://github.com/SIDN/entrada/wiki

**Comment by mashal1996** [comment]
I tried to send a message but I got this:
The group entrada only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list

**Comment by mwullink** [comment]
ah that's not correct, it should have been fixed by now.
thx.
