### ISSUE TITLE
compile to get .jar file

### ISSUE THREAD

**Issue by mashal1996** [SIDN/entrada#94]
there is no (pcap-to-parquet-2.0.2-jar-with-dependencies.jar) for the new version !!
I tried to compile it using netbeans but I got this error:
Failed to execute goal on project entrada: Could not resolve dependencies for project nl.sidnlabs:entrada:jar:2.0.3: The following artifacts could not be resolved: nl.sidnlabs:dnslib:jar:0.2.0-SNAPSHOT, nl.sidnlabs:pcap-lib:jar:0.2.2-SNAPSHOT: Failure to find nl.sidnlabs:dnslib:jar:0.2.0-SNAPSHOT in file://C:\Users\XXXX\Desktop\entrada-2.0.3/lib

**Comment by mwullink** [comment]
the dnslib and pcaplib dependencies were not correctly published to the maven central repo, this has been done by now.

are trying to compile entrada to deploy it?
you don't need to compile it then, you can deploy it using the Docker image.  

if you are using your own compiled version, you need a spring config file, see the default file here: https://github.com/SIDN/entrada/blob/master/src/main/resources/application.properties

**Comment by mashal1996** [comment]
Okk.., So what about version 0.1.3 , how can I get the correct  dnslib and pcaplib dependencies.
I have modified the code , and now I want to compile it to get jar file but the problem is it cannot resolve some dependencies.

**Comment by mwullink** [comment]
you have a modified version of entrada 0.1.3?

can't you checkout 2.0 and port to the changes to that version?
