### ISSUE TITLE
Error statistics in the new version

### ISSUE THREAD

**Issue by Aliii98** [SIDN/entrada#98]
Dear mwullink,
I currently updated my Entrada from 0.1.3 to 2.0.6, however, I can not find the errors statistics in the new version. Such as processing time, run error count, decode error, req no response errors.. etc.
Is there a way to get error statistics and data in Entrada 2.0.6? 

Kind regards,
Ali Al Badra.

**Comment by mwullink** [comment]
closed due to inactivity
